# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

if Rake::Task.task_defined?(:'db:check_protected_environments')
  Rake::Task[:'db:check_protected_environments'].clear
end
