version: '3.3'

services:
  app: &app
    build:
      context: .
      args:
        NODE_MAJOR: "12"
        YARN_VERSION: "1.22.4"
        RUBY_VERSION: ${RUBY_VERSION}
    image: bootstrap-form:latest-$RUBY_VERSION
    tmpfs:
      - /tmp

  web:
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - NODE_ENV=development
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/.bash_history
      - RAILS_ENV=test
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=web
      - TEST_APP_PORT=3001
    ports:
      - "3001:3001"
    command: /bin/bash -c "cd demo && bin/dev"

  selenium:
    image: selenium/standalone-chrome:118.0
    logging:
      driver: none
    stdin_open: true
    tty: true
    ports:
      - '4444:4444'
      - '5900:5900'
