source "https://rubygems.org"

gem "bootstrap_form", path: ".."

gem "bootsnap", require: false
gem "cssbundling-rails"
gem "htmlbeautifier"
gem "jbuilder"
gem "jsbundling-rails"
gem "propshaft"
gem "puma", ">= 5.0"
gem "rails", "~> 8.0.0"
gem "sqlite3", ">= 2.1"
gem "stimulus-rails"
gem "thruster", require: false
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "brakeman", require: false
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara-screenshot-diff", require: false
  gem "chunky_png", "~> 1.4"
  gem "selenium-webdriver"
end
