source "https://rubygems.org"

gem "bootstrap_form", path: ".."

gem "rails", "~> 7.1.1"

gem "bootsnap", require: false
gem "cssbundling-rails"
gem "htmlbeautifier"
gem "jbuilder"
gem "jsbundling-rails"
gem "puma"
gem "sprockets-rails", "< 3.5.0", require: "sprockets/railtie"
gem "sqlite3", "~> 1.4"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara-screenshot-diff"
  gem "selenium-webdriver"
end
